version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=renol114
      - POSTGRES_DB=A.E.R
    ports:
      - "5432:5432"
    volumes:
      - aer-postgres:/var/lib/postgresql/data

  api:
    build: 
      context: .
    container_name: aer_app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres 
      - POSTGRES_PASS=renol114
      - POSTGRES_PORT=5432
      - POSTGRES_DB=A.E.R 
    ports: 
      - "9090:9090"
    depends_on: 
      - db

volumes:
  backend_aer:
  aer-postgres:                  
