version: "3.8"
services:
  db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=renol114
      - POSTGRES_DB=A.E.R
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data

  app:
    build: 
      context: .
    container_name: aer_app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres 
      - POSTGRES_PASS=renol114
      - POSTGRES_PORT=5432
      - POSTGRES_DB=A.E.R 
    ports: 
      - "9090:9090"
    volumes: 
      - backend_aer:/volumes
    depends_on: 
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: b_reno@u.pacific.edu
      PGADMIN_DEFAULT_PASSWORD: renol114
    ports:
      - "5050:80"

volumes:
  backend_aer:
  database_postgres:                  
