version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - env/service/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - aer-postgres:/var/lib/postgresql/data

  api:
    build: 
      context: backend
      dockerfile: api/Dockerfile
    container_name: aer_app
    env_file:
      - env/db.env
    ports: 
      - "9090:9090"
    depends_on: 
      - postgres
    command: /app/server.bin

  migration:
    build:
      context: backend
      dockerfile: migration/Dockerfile
    container_name: aer_migration
    env_file:
      - env/db.env
    depends_on:
      - postgres
    command: /migrations/entrypoint.sh
      

volumes:
  backend_aer:
  aer-postgres:                  
