GET http://localhost:9090/

GET http://localhost:9090/athletes

GET http://localhost:9090/athletes/obpg5wDZjn/aer

GET http://localhost:9090/athletes/K7MO2pVcdE/aer



POST http://localhost:9090/athletes

{
    "first_name": "Brandon",
    "last_name": "Reno",
    "age": 27
}

PUT http://localhost:9090/athletes/obpg5wDZjn/workouts/27

{
    "date": "6/14/2021",
    "description": "Hard Workout",
    "sport": "swimming",
    "rating": 8
}



PUT http://localhost:9090/athletes/qaB18cP15n

{
    "first_name": "BRANDON",
    "last_name": "RENO",
    "age": "f:"
}

PUT http://localhost:9090/athletes/5phOA2wkBb/workouts/4

{
    "date": "5-23-2021",
    "Description" : "changed the desc!",
    "sport": "swimming",
    "rating": 3
}