GET http://localhost:9090/

GET http://localhost:9090/athletes

POST http://localhost:9090/athletes

{
    "first_name": "Brandon",
    "last_name": "Reno",
    "age": 27
}

PUT http://localhost:9090/athletes/cSZjAXKA5v

{
    "first_name": "Brandon",
    "last_name": "Ricardo",
    "age": 23
}

GET http://localhost:9090/athletes/cSZjAXKA5v/aer

GET http://localhost:9090/athletes/cSZjAXKA5v/workouts


POST http://localhost:9090/athletes/cSZjAXKA5v/workouts

{
    "date": "6/14/2021",
    "description": "Short rest 25s freestyle",
    "sport": "swimming",
    "rating": 9
}

PUT http://localhost:9090/athletes/cSZjAXKA5v/workouts/33

{
    "date": "6/21/2021",
    "description": "Short rest 25s freestyle, dolphin kick and breath holding",
    "sport": "swimming",
    "rating": 9
}

DELETE http://localhost:9090/athletes/cSZjAXKA5v

DELETE http://localhost:9090/athletes/cSZjAXKA5v/workouts/33