POST http://localhost:9090/workouts/uf23b

{
    "date": "5/13/2021",
    "description": "Hard Workout",
    "sport": "swimming",
    "rating": 3
}

GET http://localhost:9090/workouts/uf23b

GET http://localhost:9090/workouts/uf23b/5

DELETE http://localhost:9090/workouts/uf23b/5

PUT http://localhost:9090/workouts/uf23b/4

{
    "date": "5-23-2021",
    "Description" : "changed the desc!",
    "sport": "swimming",
    "rating": 3
}

GET http://localhost:9090/athlete/R5HYMiks5d

POST http://localhost:9090/athlete

{
    "first_name": "Erik",
    "last_name": "Clemensen",
    "age": 22
}

PUT http://localhost:9090/athlete/R5HYMiks5d

{
    "first_name": "Kelsey",
    "last_name": "LLoyd",
    "age": 20
}
