POST http://localhost:9090/workouts

{
    "id": 1,
    "user": {
      "athlete_id": 1,
      "name": "Brandon Reno",
      "sport": "Swimming",
      "age": 23
    },
    "date": "5/13/2021",
    "description": "Hard Workout"
}

DELETE http://localhost:9090/workouts/wid3

GET http://localhost:9090/workouts/wid3

GET http://localhost:10000/Workouts/workout1528

PUT http://localhost:9090/3

{
    "Description" : "Test 5"
}

DELETE http://localhost:10000/articles/4