POST http://localhost:9090/workouts/nTRo0jYzMV

{
    "date": "5/27/2021",
    "description": "4 100s best average",
    "sport": "swimming",
    "rating": 8
}

GET http://localhost:9090/workouts/nTRo0jYzMV

GET http://localhost:9090/workouts/uf23b/7

DELETE http://localhost:9090/workouts/uf23b/5

PUT http://localhost:9090/workouts/uf23b/4

{
    "date": "5-23-2021",
    "Description" : "changed the desc!",
    "sport": "swimming",
    "rating": 3
}

GET http://localhost:9090/athletes/nTRo0jYzMV

POST http://localhost:9090/athletes

{
    "first_name": "Brandon",
    "last_name": "Reno",
    "age": 23
}

PUT http://localhost:9090/athlete/R5HYMiks5d

{
    "first_name": "Kelsey",
    "last_name": "LLoyd",
    "age": 20
}
